// === PATTERN LIBRARY ===
const PATTERN_CATS = [
  { id: 'basics', name: 'Basics' },
  { id: 'motifs', name: 'Motifs' },
  { id: 'borders', name: 'Borders' },
  { id: 'transition', name: 'Transition' },
  { id: 'allover', name: 'All-Over' }
];

const PATTERN_LIB = [
      {
        id: 'f_d0c92db0749f',
        name: 'mushrooms',
        cat: 'motifs',
        grid: [
        '------x---x------x-----x',
        '--x------x-----x---x----',
        '---x---x-----x---x----x-',
        '-x-------x----------x---',
        '---xxxx----x---xxxx----x',
        '--xxxxxx------xxxxxx----',
        '--xxx-xx--x---xx-xxx--x-',
        '-xxxxxxxx----xxxxxxxx---',
        'xxxx-xxxxx--xxxxx-xxxx--',
        'xxxxxxx-xx--xx-xxxxxxx--',
        'xxx-xxxxxx--xxxxxx-xxx--',
        'xxxxx-xxxx--xxxx-xxxxx--',
        '---xxxx--------xxxx-----',
        '---xxxx---x----xxxx---x-',
        '-x-xxxx-x------xxxx-----',
        '-x-xxxx-x------xxxx-----',
        '-x-xxxx-x---x--xxxx--x--',
        'x--xxxx--x--x--xxxx--x--',
        'x--xxxx--x-x---xxxx---x-',
        'x---xx---x-x----xx----x-',
        '--x----x--x--x------x--x',
        '-----x----x----x-------x',
        '-x----x---x---x---x----x',
        '---x----x---x---x-------'
        ]
      }
,
      {
        id: 'f_384faa36407f',
        name: 'repeated small roses',
        cat: 'motifs',
        grid: [
        'xx--------xxxx--------xx',
        '-xxx-----xxx-xxx-----xxx',
        'xx--x----xx-xx--x----xx-',
        'xx--x-----x-xx--x-----x-',
        'xxxxxx--xxx-xxxxxx--xxx-',
        '-xxx-x--xxxx-xxx-x--xxxx',
        'x---xx---xx-x---xx---xx-',
        'xxxxx-----xxxxxxx-----xx',
        'xx-xx------xxx-xx------x',
        'xx----------xx----------',
        '----xxxx--------xxxx----',
        '---xxx-xxx-----xxx-xxx--',
        '---xx-xx--x----xx-xx--x-',
        '----x-xx--x-----x-xx--x-',
        '--xxx-xxxxxx--xxx-xxxxxx',
        '--xxxx-xxx-x--xxxx-xxx-x',
        '---xx-x---xx---xx-x---xx',
        '----xxxxxxx-----xxxxxxx-',
        '-----xxx-xx------xxx-xx-',
        '------xx----------xx----'
        ]
      }
,
      {
        id: 'f_c5907b6fc422',
        name: 'anchor',
        cat: 'motifs',
        grid: [
        '---------xxxxxx---------',
        '-------xxxxxxxxxx-------',
        '-------xxxxxxxxxxxx-----',
        '----xx--xxxxxxxxxxxx----',
        '----xxx-xx----xxxxxx----',
        '---xxxx---------xxxxx---',
        '---xxxx----------xxx----',
        '--xxxxx----xx----xxx-x--',
        '--xxxx----xxxx----x--x--',
        '--xxxx----x--x------xx--',
        '-xxxx-----xxxx-----xxxx-',
        '-xxxx------xx------xxxx-',
        '-xxxx------xx------xxxx-',
        '-xxxx----xxxxxx----xxxx-',
        '-xxxx------xx------xxxx-',
        '-xxxx------xx------xxxx-',
        '-xxxx------xx------xxxx-',
        '-xxx-------xx------xxxx-',
        '-xx--------xx------xxxx-',
        '-x--xx--x--xx--x--xxxx--',
        '-x-xxx--xx-xx-xx--xxxx--',
        '---xxxx--xxxxxx--xxxxx--',
        '---xxxx----xx----xxxx---',
        '---xxxxx---------xxxx---',
        '----xxxxxx----xx--xx----',
        '----xxxxxxxxxxxxx--x----',
        '-----xxxxxxxxxxxxx------',
        '-------xxxxxxxxxx-------',
        '---------xxxxxx---------'
        ]
      }
,
      {
        id: 'f_e101db1c04f5',
        name: 'geometric border 1',
        cat: 'borders',
        grid: [
        '-xx--xxx--xx-xx--xxx--xx',
        'x--x-xxx-x--x--x-xxx-x--',
        'xx--xxxxx--xxx--xxxxx--x',
        'xxx--xxx--xxxxx--xxx--xx',
        'xx--xxxxx--xxx--xxxxx--x',
        'x--xx---xx--x--xx---xx--',
        '--xx-----xx---xx-----xx-',
        'x--xx---xx--x--xx---xx--',
        'xx--xxxxx--xxx--xxxxx--x',
        'xxx--xxx--xxxxx--xxx--xx',
        'xx--xxxxx--xxx--xxxxx--x',
        'x--x-xxx-x--x--x-xxx-x--',
        '-xx--xxx--xx-xx--xxx--xx'
        ]
      }
,
      {
        id: 'f_3a3981769ead',
        name: 'wave border 1',
        cat: 'borders',
        grid: [
        'x-----x-----x-----x-----',
        'xx---xxx---xxx---xxx---x',
        '-xxxxx-xxxxx-xxxxx-xxxxx',
        '--xxx---xxx---xxx---xxx-'
        ]
      }
,
      {
        id: 'f_e9d5156990b7',
        name: 'zig zag 1',
        cat: 'borders',
        grid: [
        '-----x-----x-----x-----x',
        'x---xxx---xxx---xxx---xx',
        'xx-xx-xx-xx-xx-xx-xx-xx-',
        '-xxx---xxx---xxx---xxx--',
        '--x-----x-----x-----x---'
        ]
      }
,
      {
        id: 'f_63592b36dd9d',
        name: 'butterfly motif',
        cat: 'motifs',
        grid: [
        'xx----xxxx----xxxx----xx',
        'x----x---xx--xx---x----x',
        '-x--xx-x--xxxx--x-xx--x-',
        '-xx-xx-xx--xx--xx-xx-xx-',
        '-x---xxxxx-xx-xxxxx---x-',
        'x-----xxx--xx--xxx-----x',
        'xx---x----xxxx----x---xx',
        '-xxxx--xxxx--xxxx--xxxx-',
        '-xxxx--xxxx--xxxx--xxxx-',
        'xx---x----xxxx----x---xx',
        'x-----xxx--xx--xxx-----x',
        '-x---xxxxx-xx-xxxxx---x-',
        '-xx-xx-xx--xx--xx-xx-xx-',
        '-x--xx-x--xxxx--x-xx--x-',
        'x----x---xx--xx---x----x',
        'xx----xxxx----xxxx----xx'
        ]
      }
,
      {
        id: 'f_cd61d12c5dc4',
        name: 'tf big moth',
        cat: 'motifs',
        grid: [
        'x---x---xxx-------x-----',
        'x------xxxxx-----x-x----',
        'x------xxxxxx-----x-----',
        'xx------xxxxxx--x------x',
        'xxxx----xxxxxxx------xxx',
        'xx------xxxxxxx----x---x',
        'x-----x--xxxx-xx-----x--',
        'x----x-x-xxx-xxx--x-----',
        'x-----x--xx--xx-x-------',
        '---x-----xx-xx-x-x--x---',
        '-------x-xx-xxx-xx--x--x',
        '-x-------xx-xxxxxx--x---',
        '----x----xx--xx-xxx-x---',
        '------x---xx---xxxx-x-xx',
        '--x-------xxxxxxxx--xxx-',
        '----x------xxxxxxx-xxx--',
        '---x-x---xx-xxxxx-xxx---',
        '----x---xxxx--xxx-xxx-x-',
        'x-------xxxxxx----xxx-xx',
        'xx------xx-xxxxxx--x-xxx',
        'xxx------x---xxxx---xxxx',
        '-xxxx----xxx-xxx--x-xxxx',
        'x-xxxx----xx-xxx--x-xxx-',
        '-xx-xxx---xx--x--xx-xxxx',
        'xxx--xx---xxxxx-xxx-xxx-',
        'xxx-xxxx---xxx--xxxx-xx-',
        '-xx-xxxx---xxx-xx-xx-xx-',
        '----xxxx---xx--xx-xxx-xx',
        'x--xxxxx---xx-xxx--xx-xx',
        'xxx--xxx---x-xxxxx-xx-xx',
        'xx----x---xx-xxxxx--xx-x',
        'x--x-----xx-xxx--xxxxx-x',
        '--x-x----xx-xx---xxxxx--',
        '---x----xx-xx-----xxxx--',
        '-x-----xxx-xx------xxx--',
        '----x-xxx-xx----x---xx--',
        '------xx--xx----x------x',
        'x----xx--xx-----x-----x-',
        '----xx---xx----xxx-----x',
        '--x------xx--xxxxxxx----',
        '----x----x-----xxx---x--',
        'x-------xx------x-------',
        '-x------x---x---x------x',
        'x-------x-------x--x----'
        ]
      }
,
      {
        id: 'f_f40bacd2bacf',
        name: 'tf moon stars',
        cat: 'motifs',
        grid: [
        '----xx--x-------x-----x-',
        '---xx-------x---x--x----',
        '--xxx-----x-----x-----x-',
        '-xxx-------x---xxx---x--',
        '-xxx----x---x--xxx--x---',
        '-xx--x-------x-xxx-x----',
        'xxx-------x----x-x------',
        'xxx---x------xxx-xxx----',
        'xxx-------xxxxx---xxxxx-',
        'xxx----x---xxxx---xxxx--',
        'xxxx--x-x----xxx-xxx----',
        'xxxx---x-------x-x------',
        'xxxxx----x-----xxx---x--',
        '-xxxxx--xx---x-xxx-x----',
        '-xxxxxxxx---x--xxx--x---',
        '--xxxxxxx--x----x----x--',
        '---xxxxx--x-----x-----x-',
        'x---xxx-----x---x-------'
        ]
      }
,
      {
        id: 'f_70e2e4b87414',
        name: 'tf small moth',
        cat: 'motifs',
        grid: [
        'xx-------x---x-------xxx',
        'xxx-----xxx-xxx-----xxx-',
        'xxxx----xxxxxxx----xxxxx',
        '-x-x----xxxxxxx----x-x-x',
        '-x-xx----xxxxx----xx-x--',
        'xxxxxx----xxx----xxxxxx-',
        'xx-x-xx----x----xx-x-xx-',
        '-x-xx-xx-------xx-xx-x-x',
        '-xx-xxxx-------xxxx-xx-x',
        '--x-xx-xx-----xx-xx-x--x',
        '--xxxx-xx-----xx-xxxx--x',
        '--xxx---xx---xx---xxx--x',
        '---x-----x---x-----x---x',
        'x--xx---xxx-xxx---xx--xx',
        'x--xxx-xxxx-xxxx-xxx--xx',
        'x---xx-xxxx-xxxx-xx---xx',
        'x-x-xxxxxx---xxxxxx-x-xx',
        'x-x--xxxx--x--xxxx--x-xx',
        '----x-xxx-x-x-xxx-x----x',
        '-xxx--xx---x---xx--xxx-x'
        ]
      }
,
      {
        id: 'f_18ba4df5a03c',
        name: 'tf flowers',
        cat: 'motifs',
        grid: [
        '-x------x--x---x-x-----x',
        '-x------x--x---x-x-x---x',
        'xx----x-xx-x---xxxxx---x',
        'xx-x--xxxxxx---xxxx----x',
        'xxxx---xxxxx---xxxxxx--x',
        'xxx-----xxxx----xxxx---x',
        'xx-------xx-----xxx-----',
        '-----xxx--x----x-------x',
        '---xxxxx--xx---x---x--xx',
        '-xxxxxx-x--x--xx--xx--x-',
        '--xxx----x-x--x---xx-xx-',
        'x------x--xx--x--xx-xx--',
        '----x--xx--x-xx--xx-x---',
        '--x-----xx-x-x----xx-xx-',
        '-----x--xx-x-xxxxx--xxxx',
        '--xx----xxxx-x-------xx-',
        'x--xx----xxx-x---x------',
        '---xxx----xxxx-----x--x-',
        '-x--xxx-----x-----xx----',
        'xx---xx---x-x-----xx---x',
        'x------x-xx-x--x--x--xxx',
        '--x----x-x--xx-x-xxxx---',
        '-----x--x----x-x-x----x-',
        '--x------xx--x--x---x---',
        '--x--------xxxx-x---x---',
        '-x---xxxxxx---x-x----x-x',
        'x-----xxxx----xx---x--xx',
        'x---x-------x--x------x-',
        'x------x-------x-x----x-'
        ]
      }
,
      {
        id: 'f_bbc4d224473e',
        name: 'tf big flower',
        cat: 'motifs',
        grid: [
        '---x----x-----x----x----',
        '-x---xx---xxx---xx---x--',
        'xxx-xxxx-xxxxx-xxxx-xxx-',
        'xxx-xxxx-xxxxx-xxxx-xxx-',
        'xxxx-xxx-xxxxx-xxx-xxxx-',
        '-xxx-xxx-xxxxx-xxx-xxx--',
        '-xxx-xxxx-xxx-xxxx-xxx--',
        '-xxxx-xxx-xxx-xxx-xxxx--',
        '--xxx-xxx-xxx-xxx-xxx--x',
        '--xxxx-xx-xxx-xx-xxxx---',
        'x--xxx-xxx-x-xxx-xxx----',
        '----xxx-xx-x-xx-xxx--x--',
        '-----xxx-xxxxx-xxx-----x',
        'x-----xxx-xxx-xxx-----x-',
        '--------xxxxxxx--------x',
        '---xxx-----x-----xxx----',
        '--xxxxx----x----xxxxx---',
        '--xxxxx----x----xxxxx---',
        '--xx-xxx---x---xxx-xx---',
        '--xxx-xxx--x--xxx-xxx---',
        '--xxxx-xx--x--xx-xxxx---',
        '---xxxx-xx-x-xx-xxxx---x',
        'x----xxx-x-x-x-xxx----x-',
        '-------xx-xxx-xx-------x',
        '--xx-----xxxxx-----xx---',
        '-xxxxx-----x-----xxxxx--',
        '-xx-xxx----x----xxx-xx--',
        '-xxx-xxx---x---xxx-xxx--',
        '--xxx--xx--x--xx--xxx---',
        '--xxxxx-xx-x-xx-xxxxx---',
        '---xxxxx-x-x-x-xxxxx---x',
        'x---xxxxx-xxx-xxxxx---x-',
        '------xxxx-x-xxxx------x',
        '--xxx------x------xxx---',
        '-xxxxx-----x-----xxxxx--',
        '-xxxxxxx---x---xxxxxxx--',
        '-xx--xxxx--x--xxxx--xx--',
        '--xxx---xx-x-xx---xxx--x',
        'x--xxxxx--xxx--xxxxx--x-',
        '------xxxxx-xxxxx------x'
        ]
      }
,
      {
        id: 'f_99588216dfff',
        name: 'owl',
        cat: 'motifs',
        grid: [
        '--xxx-----x----x------x-',
        '-xxxx--xxx--xx---xxxx---',
        'xx-xx-x-x--xxxx--xx-xx--',
        'x-xx-x-xx-xx--xx--xx-xx-',
        'xxx--xxx---xxx-x--xxx-x-',
        'xx---xx------xxxx--xxxx-',
        'x---x---x-xx-----------x',
        '----xx----xxx------xxx-x',
        'x--xxxx----xxxxxxxxx-x--',
        '-xxx--xx---xx-x-x-x-x---',
        '-x-xxx-x--xxxx-x-xxxx---',
        'xx--xxxx-xx---x-x---xx--',
        'x-x------xx---xxx----x-x',
        'x-x------x-----x-----x-x',
        'x-x-----xx--xx---xx--x-x',
        'x-x--x--xx---x----x--x-x',
        'xxx-----xxx----x-----x--',
        'xx----x-xxxx---x----xx--',
        '---x----xx-xxx-x-xxxx---',
        'x------xx-xx-------xx---',
        '--x---xxx-xx----x--xx---',
        '---x--xx-xxx--x-----xx--',
        '-----xxx-xxx--x---x-xx--',
        '-x---xxx-xxx---x----xx--',
        '----xxx-xxx--x-x-x--x--x',
        '----xxx-xxx----x-x--x-x-',
        '--x-xx-xxx---x---x--x---',
        'x---x-xx---x--x----x----',
        '---xxxx---x---x--x-x-x--',
        '---xxxx-x-x-x--x---x---x',
        '---xxxx---x----x---x----',
        'xx-xxxx--x---x--x-x---x-',
        'xx-xxxx--x-x--x--xx--xx-',
        'x--xxxx--x------xxx-xx-x',
        'x--xxxx----xx-xxxx--x-xx',
        '---xxxx--xxxxxxxxx--xxxx',
        '-x-xxxx-xxxxx----xxxx---',
        '----xxxxx-xxx-----x----x',
        '--x-xxxx---xx----xxxxxx-',
        'x---xx-----x----xx--xx--',
        '----x-----xxxxxx---xxxx-',
        '-x-x------xxxxxx-x-xx-xx',
        '---x-----xxx-xx--x-xx-xx',
        '---x----xxx-xxx-x--xx-xx',
        '--x----xx-x-xx--x--xxx-x',
        '--x----xx-x-xx-xxx--xx-x',
        '--x----xx-xxx--x-xx-xx-x',
        '-x----x-xxxx---x-xx--xxx',
        '-x----x-xxx----xx-x---x-',
        '-x---xxxxx---x-xxxx---x-',
        '-x---x------x---xx--x---',
        '----x-----x------x-----x',
        '--x-x---x----x-----x----'
        ]
      }
,
      {
        id: 'f_9066245bc3fe',
        name: 'triangles',
        cat: 'borders',
        grid: [
        'xxxxxxx-xxxxxxx-xxxxxxx-',
        '-xxxxx---xxxxx---xxxxx--',
        '--xxx-----xxx-----xxx---',
        '---x-------x-------x----'
        ]
      }
,
      {
        id: 'f_875a438b0ef5',
        name: 'dress',
        cat: 'motifs',
        grid: [
        'x---xx---xx--xx---xx---x',
        'x-x-xx--xxx--xxx--xx-x-x',
        'x-x-xx-xx--xx--xx-xx-x-x',
        'x-xxx--xx--xx--xx--xxx-x',
        'xxxxx--xxx-xx-xxx--xxxxx',
        'xxxx---xxx-xx-xxx---xxxx',
        '-xxx-------xx-------xxx-',
        '--x-------xxxx-------x--',
        '-xx-------xxxx-------xx-',
        'xx-------xx--xx-------xx',
        'xx-------x----x-------xx',
        'x-------xxx--xxx-------x',
        'x-xxx---xxxxxxxx---xxx-x',
        'x-xxx--xxxxxxxxxx--xxx-x',
        'x--xx--xxx-xx-xxx--xx--x',
        'x--xx-xx-x-xx-x-xx-xx--x',
        '-xxx--xx-x-xx-x-xx--xxx-',
        '-xx---xx---xx---xx---xx-'
        ]
      }
,
      {
        id: 'f_0a18495db76a',
        name: 'chicken',
        cat: 'motifs',
        grid: [
        '--x--------xx--xx-xx---x',
        '-xx--x-----xx-xxx--x----',
        '---xx-xxxx-x--xx-----xx-',
        '--xxx---x---xx-------xx-',
        '-xx---------xx----------',
        '-x--x-xx-xxx--x--xxx--x-',
        'xx--x-xx--xx--x-xxxxx-xx',
        'x-----xxx-------xxxxx---',
        'x--x---xx----xxxxxxxxxx-',
        'x--xx--xxx-xxxxxxxxxx---',
        'x---xx--xx-xxxxxxxxxx---',
        'x----x--xxxxxxxxxxxxx---',
        'xx-x-x--xxxxxxxxxxxxx---',
        '-x-x-x--xxxxxxxxxxxxx---',
        '-x--xx---xxxxxxxxxxx----',
        '-x--xx---xxxxxxxxxxx----',
        '-x-xx-----xxxxxxxxx-----',
        '-xxxx-x-x--xxxxxxx---xx-',
        '-xxx--xxx---xxxxx----xx-',
        '--xx---xx-----x-----x---',
        '--xx---x--x---x----xx---',
        '-xxxx-xxxxx--xxx---x---x'
        ]
      }
,
      {
        id: 'f_41f2fa390ec6',
        name: 'climbing roses',
        cat: 'motifs',
        grid: [
        '------x-----x-x---xxx---',
        '--xxx-xxx---xxx--xxx----',
        '-x--xx-xx-----x-xx------',
        '-x--xx-x-------x--------',
        '-xxxxx-xxx-----x----xxx-',
        'x-xxx-xxxx------x--xxx--',
        'xx---x-xx---xxx--x-xx---',
        '-xxxxxx----xx-x---x-----',
        '-xxxxxx---x---x----x----',
        '---xxx-x--x-xx-----x----',
        '-------xx-xxxx------x---',
        '--------xx----------x---',
        '--xx-----x-----------x--',
        '---xxx---x-xx----x------',
        '----xxx--xxx---xxx-xxx--',
        '------xx-x-----xx-xx--x-',
        '--------x-------x-xx--x-',
        '-xxx----x-----xxx-xxxxx-',
        '--xxx--x------xxxx-xxx-x',
        '---xx-x--xxx---xx-x---xx',
        '-----x---x-xx----xxxxxx-',
        '----x----x---x---xxxxxx-',
        '----------xx-x--x-xxx---',
        '---x------xxxx-xx-------',
        '---x----------xx--------',
        '--x-----------x-----xx--',
        '------x-----x-x---xxx---',
        '--xxx-xxx---xxx--xxx----',
        '-x--xx-xx-----x-xx------',
        '-x--xx-x-------x--------',
        '-xxxxx-xxx-----x----xxx-',
        'x-xxx-xxxx------x--xxx--',
        'xx---x-xx---xxx--x-xx---',
        '-xxxxxx----xx-x---x-----',
        '-xxxxxx---x---x----x----',
        '---xxx-x--x-xx-----x----',
        '-------xx-xxxx------x---',
        '--------xx----------x---',
        '--xx-----x-----------x--',
        '---xxx---x-xx----x------',
        '----xxx--xxx---xxx-xxx--',
        '------xx-x-----xx-xx--x-',
        '--------x-------x-xx--x-',
        '-xxx----x-----xxx-xxxxx-',
        '--xxx--x------xxxx-xxx-x',
        '---xx-x--xxx---xx-x---xx',
        '-----x---x-xx----xxxxxx-',
        '----x----x---x---xxxxxx-',
        '----x-----xx-x--x-xxx---',
        '---x------xxxx-xx-------',
        '---x----------xx--------',
        'xxx-----------x-----xx--'
        ]
      }

,
      {
        id: 'f_b53392a54611',
        name: 'weave to lace',
        cat: 'motifs',
        grid: [
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x---x---x---x---',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x---x---x---x---',
        'x---x---x---x---x---x---',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x---x---x---x---',
        'x---x---x---x---x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---',
        'x---x---x---x---x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---'
        ]
      }
,
      {
        id: 'f_12f56e8e3e02',
        name: 'fancy diamond',
        cat: 'borders',
        grid: [
        '----x-------x-------x---',
        '--xx-xx---xx-xx---xx-xx-',
        '-x-----x-x-----x-x-----x',
        'x---x---x---x---x---x---',
        '-xx-x-xx-xx-x-xx-xx-x-xx',
        '---xxx-----xxx-----xxx--',
        '---xxx-----xxx-----xxx--',
        '--xx-xx---xx-xx---xx-xx-',
        '--xx-xx---xx-xx---xx-xx-',
        '-xx---xx-xx---xx-xx---x-',
        '-xx---xx-xx---xx-xx---xx',
        'xx-----xxx-----xxx-----x',
        'xx-----xxx-----xxx-----x',
        '-xx---xx-xx---xx-xx---xx',
        'xx-----xxx-----xxx-----x',
        'xx-----xxx-----xxx-----x',
        '-xx---xx-xx---xx-xx---xx',
        '-xx---xx-xx---xx-xx---xx',
        '--xx-xx---xx-xx---xx-xx-',
        '--xx-xx---xx-xx---xx-xx-',
        '---xxx-----xxx-----xxx--',
        '---xxx-----xxx-----xxx--',
        '-xx-x-xx-xx-x-xx-xx-x-xx',
        'x---x---x---x---x---x---',
        '-x-----x-x-----x-x-----x',
        '--xx-xx---xx-xx---xx-xx-',
        '----x-------x-------x---'
        ]
      }
,
      {
        id: 'f_09fee34178a4',
        name: 'diagonal 1',
        cat: 'borders',
        grid: [
        'xx--xx--xx--xx--xx--xx--',
        '-xx--xx--xx--xx--xx--xx-',
        '--xx--xx--xx--xx--xx--xx',
        'x--xx--xx--xx--xx--xx--x'
        ]
      }
,
      {
        id: 'f_e7bf60a201a0',
        name: 'diagonal 2',
        cat: 'borders',
        grid: [
        'x--xx--xx--xx--xx--xx--x',
        '--xx--xx--xx--xx--xx--xx',
        '-xx--xx--xx--xx--xx--xx-',
        'xx--xx--xx--xx--xx--xx--'
        ]
      }

,
      {
        id: 'f_2c6ef7e47b2d',
        name: 'suns and braids',
        cat: 'motifs',
        grid: [
        '---x-------x-------x---x',
        '-------x---x---x-------x',
        '-x--x---x--x--x---x--x--',
        'x----x---x-x-x---x----x-',
        '------x---------x------x',
        'x--x---x--xxx--x---x--x-',
        '-x--x----xxxxx----x--x--',
        '-x---x--xxxxxxx--x---x--',
        'x-------xxxxxxx-------x-',
        '---xxxx-xxxxxxx-xxxx---x',
        'x-------xxxxxxx-------x-',
        '-x---x--xxxxxxx--x---x--',
        '-x--x----xxxxx----x--x--',
        'x--x---x--xxx--x---x--x-',
        '------x---------x------x',
        'x----x---x-x-x---x----x-',
        '-x--x---x--x--x---x--x--',
        '-------x---x---x-------x',
        '---x-------x-------x---x',
        '--x---x--x---x--x---x--x',
        '-x---x----x-x----x---x-x',
        '----x------x------x-----',
        'x--x---x--x-x--x---x--xx',
        'xx----x--x---x--x----xxx',
        'xxx--x---x---x---x--xxxx',
        'xxx-------x-x-------xxxx',
        'xxx-xxxx---x---xxxx-xxxx',
        'xxx-------x-x-------xxxx',
        'xxx--x---x---x---x--xxxx',
        'xx----x--x------x----xxx',
        'x--x---x--x-x--x---x--xx',
        '----x------x------x-----',
        '-x---x----x-x----x---x-x',
        '--x---x--x---x--x---x--x'
        ]
      }
,
      {
        id: 'f_33f393ecaf6e',
        name: 'large butterfly',
        cat: 'motifs',
        grid: [
        '-------x---------x------',
        '--------x-------x-------',
        '--xx-x---x-----x---x-xx-',
        '--xxxxxxxxx---xxxxxxxxx-',
        '--x-xx-xxx-x-x-xxx-xx-x-',
        '--xx-xx-xxx-x-xxx-xx-xx-',
        '--xxxxxxxxxx-xxxxxxxxxx-',
        '---xxxxx-xxx-xxx-xxxxx--',
        '---xxxx---xx-xx---xxxx--',
        '-----x-x-xx---xx-x-x----',
        '----xxxxxxx---xxxxxxx---',
        '---xxxx-xxxx-xxxx-xxxx--',
        '--xx-x-xx-xx-xx-xx-x-xx-',
        '--x---xx-xxx-xxx-xx---x-',
        '--xx-xxxxxx---xxxxxx-xx-',
        '---xxx-xxx-----xxx-xxx--'
        ]
      }
,
      {
        id: 'f_62a9b97a6b0d',
        name: 'diamonds',
        cat: 'borders',
        grid: [
        '-xx---xx-xx---xx-xx---xx',
        'xx--x--xxx--x--xxx--x--x',
        'x--xxx--x--xxx--x--xxx--',
        '--xx-xx---xx-xx---xx-xx-',
        'x--xxx--x--xxx--x--xxx--',
        'xx--x--xxx--x--xxx--x--x',
        '-xx---xx-xx---xx-xx---xx',
        'xx--x--xxx--x--xxx--x--x',
        'x--xxx--x--xxx--x--xxx--',
        '--xx-xx---xx-xx---xx-xx-',
        'x--xxx--x--xxx--x--xxx--',
        'xx--x--xxx--x--xxx--x--x'
        ]
      }
,
      {
        id: 'f_2831a8e535b0',
        name: 'moth transition',
        cat: 'transition',
        grid: [
        'xx-xxxxx--xxxx-xxxxx--xx',
        'x-x-xxx----xx-x-xxx----x',
        'xx-xxx-x---xxx-xxx-x---x',
        'xxxx----x--xxxxx----x--x',
        'xxx--x--x--xxxx--x--x--x',
        'xx----xx--xxxx----xx--xx',
        '--x-----xxxx--x-----xxxx',
        'xx-xxxxx----xx-xxxxx----',
        '--xxxx--xx----xxxx--xx--',
        '---xx-xx-xx----xx-xx-xx-',
        '----xxxx-xx-----xxxx-xx-',
        '--x---x-xxx---x---x-xxx-',
        '-x-x---xxxx--x-x---xxxx-',
        '--x-----xx----x-----xx--'
        ]
      }
,
      {
        id: 'f_390313ce0b1e',
        name: 'bloom',
        cat: 'motifs',
        grid: [
        '------------------------',
        '--x------x-----x------x-',
        '-xx------xx----x------xx',
        '-x--xxx--xx---xx--xxx--x',
        '-x--xxx--xx---xx--xxx--x',
        'xx---xxx-xx-x-xx-xxx---x',
        'x-----xx-xx-x-xx-xx-----',
        'x-----xxx-x-x-x-xxx-----',
        '-xxxx-xxxxxx-xxxxxx-xxxx',
        '-xxxx-xxxxxx-xxxxxx-xxxx',
        '--xxx-xxx-xx-xx-xxx-xxx-',
        'x-xxxx-xx-xx-xx-xx-xxxx-',
        'x--xxxx-x-xx-xx-x-xxxx--',
        '-x--xxxx--xx-xx--xxxxx-x',
        '-x--xxxx--xx-xx--xxxx--x',
        '-xx--xxxxxxxxxxxxxxx--xx',
        '-xx--xxxxxxxxxxxxxxx--xx',
        '-xx---xxxxx-x-xxxxx---xx',
        '-xx---xxxxxxxxxxxxx---xx',
        '-xx---xxx-xxxxx-xxx---xx',
        '-x-----xxxxxxxxxxxx----x',
        'xx-----xxxxx-xxxxx-----x',
        'x--------xxxxxxxx-------',
        'x--------xx-x-xx--------',
        'x---xxx--xx-x-xx--xx----',
        'x---xxx-----x-----xxx---',
        'x--xxx--xx--x--xx-xxxx--',
        'x--xxx-xxx--x--xxx-xxx--',
        'x-xxx--x--x-x-x--x--xxx-',
        'x-xxx--xx-xxxxx--x--xxx-',
        'x-xx----x--xxx--x----xx-',
        'x-x---xxx-xxxxx-xxx--xx-',
        'x-x---xx--xxxxx--xx---x-',
        'xxx--xxx---xxxx---xx--xx',
        '-x---xx----xxx----xx---x',
        '-x--xxx---xxxxx---xxx--x',
        '-xx-xxx---xxxxx---xxx-xx',
        '-xx-xx----x-x-x----xx-xx',
        '-xxxxx---xx-x-xx---xxxxx',
        '--xx-----xx-x-xx-----xx-',
        '---xxx-xx--xxx--xx-xxx--',
        '---xxx-xx--x-x--xx-xxx--',
        'x-----xx--xx-xx--xx-----',
        'x--x--xx--x---x--xx---x-'
        ]
      }
,
      {
        id: 'f_eaab321749a5',
        name: 'jaunty horse',
        cat: 'motifs',
        grid: [
        '-------x----x----x-x---x',
        '--x------x------xxxx----',
        '-----x-----x---xxxxx--x-',
        'x-------x-----xx-xx-x---',
        '---x------x--xxxxxxx----',
        '------x------xx-xxx-x--x',
        '-x-------x------xxxx-x--',
        '-----x------x---xxx-x---',
        '---xx-xxxxx----xxxxx-x--',
        '--xx-xxx-xxxxxxx-xx-x---',
        '-xx--x-xxxxxx-xxxxx--x--',
        'xx-x-xxxxx-xxxxxx-x-----',
        'x-x--xx-xxxxxx-xxxx-----',
        '--x--xxxxxx-xxxxxxx-----',
        '----xxxxx-xxxxxxxx-xx---',
        '----xxxxx--xxx-xxx-xxxx-',
        'x---xxx--xx----xxx----x-',
        '-----xx--xxx---xxxxxx-x-',
        '------xx-xx--------xx-x-',
        '------xx--xx-------xx-x-',
        '-------xx--x-------x--x-',
        '-------xx--xx------x-xx-',
        '--------xx--xx----xx-xx-',
        '--------xxx-xx----xx----',
        '--x------xx--xx--xx-----',
        '---------xx--xx--x-----x'
        ]
      }
,
      {
        id: 'f_5664f4cacf2a',
        name: 'weave overshot',
        cat: 'motifs',
        grid: [
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x---x---x---x---',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x---x---x---x---',
        'x---x---x---x---x---x---',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '-x---x---x-----x---x---x',
        'x---x---x-------x---x---',
        'x---x---x-------x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---',
        'x---x---x---x---x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---',
        '-x---x---x-----x---x---x',
        '--x---x---x---x---x---x-',
        '---x---x---x-x---x---x--',
        'x---x---x---x---x---x---'
        ]
      }
];
